wraithgar/api.lift.zone

.travis.yml
config/ci.json
config/production.json

Closes https://github.com/wraithgar/lift.zone/issues/3

Add Travis CI

---

config/default.json
controllers/activities/history.js
controllers/activities/list.js
db/activities_one_history_count.sql
lib/utils.js
test/activities/history.js
test/activities/index.js

Closes https://github.com/wraithgar/lift.zone/issues/9

paginate activity history

---

config/default.json
package.json
test/activities/history.js
test/activities/index.js

Hapi pagination 1.13.0

---

config/production.json
package.json
server.js

update to latest v6 node engine

---

test/activities/index.js

Closes https://github.com/wraithgar/lift.zone/issues/39

Test race condition

---

lib/https.js
server.js

auto redirect to https

---

package.json

Closes #75
https://greenkeeper.io/

fix(package): update aws-sdk to version 2.45.0

---

package.json

fix(package): update aws-sdk to version 2.49.0

---

package.json

fix(package): update aws-sdk to version 2.57.0

---

package.json

fix(package): update hapi to version 16.4.0

---

package.json

fix(package): update aws-sdk to version 2.70.0

---

package.json

fix(package): update aws-sdk to version 2.77.0

---

package.json

fix(package): update aws-sdk to version 2.83.0

---

package.json

fix(package): update aws-sdk to version 2.88.0

---

package.json

fix(package): update aws-sdk to version 2.90.0

---

package.json

fix(package): update aws-sdk to version 2.94.0

---

package.json

fix(package): update aws-sdk to version 2.100.0

---

package.json

fix(package): update aws-sdk to version 2.106.0

---

package.json

fix(package): update aws-sdk to version 2.118.0

---

package.json

fix(package): update joi to version 11.3.4

---

package.json

fix(package): update aws-sdk to version 2.133.0

---

package.json

fix(package): update hapi to version 16.6.2

---

package.json

fix(package): update joi to version 13.0.0

---

package.json

fix(package): update hapi-swagger to version 8.0.0

---

package.json

fix(package): update aws-sdk to version 2.141.0

---

controllers/users/recover.js
package-lock.json
package.json
test/users/recover.js

chore(package): update lab to version 15.1.1

---

package.json

fix(package): update aws-sdk to version 2.180.0

---

package.json

fix(package): update getconfig to version 4.4.1

---

package.json

fix(package): update hapi-swagger to version 9.1.1

---

package.json

fix(package): update aws-sdk to version 2.205.0

---

package.json

fix(package): update aws-sdk to version 2.214.1

---

package.json

fix(package): update aws-sdk to version 2.222.1

---

package.json

fix(package): update joi to version 13.2.0

---

package.json

fix(package): update aws-sdk to version 2.250.1

---

package.json

fix(package): update hapi-pino to version 5.0.1

---

package.json

fix(package): update aws-sdk to version 2.296.0

---

package.json

fix(package): update aws-sdk to version 2.312.0

---

package-lock.json
package.json
routes.js

Greenkeeper/keyfob 2.0.1

---

package-lock.json
package.json

Greenkeeper/@hapi/joi 16.1.1

---

package-lock.json
package.json

Greenkeeper/@hapi/boom 7.4.5
